name: Server

on:
  push:
    branches: ["**"]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[build-server]') || contains(github.event.head_commit.message, '[build-all]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy backend
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete --exclude=node_modules"
          SOURCE: "backend/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/hello_vivilrajs/server"
          EXCLUDE: ".env"

      - name: Install deps & restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hello_vivilrajs/server
            npm install
            pm2 restart server || pm2 start npm --name "server" -- run dev